### ISSUE TITLE
chain2stats.py and bx-python

### ISSUE THREAD

**Issue by sebastian-luna-valero** [cgat-developers/cgat-apps#16]
`chain2stats.py` still depends on `bx-python`:
https://github.com/cgat-developers/cgat-apps/blob/master/CGAT/tools/chain2stats.py#L221

Its test is currently disabled:
https://github.com/cgat-developers/cgat-apps/blob/master/tests/chain2stats.py/tests.yaml#L8

How important is this script? Either we get rid of it or we add `bx-python` back as a dependency.

Please let me know your thoughts.

**Comment by Acribbs** [comment]
Don’t think Iv ever used it

**Comment by sebastian-luna-valero** [comment]
Thanks, Adam.

It looks like it's not a popular script, so presumably it can be deleted.

There are two other scripts that might be related, and I wonder whether they can also be deleted:
* `CGAT/tools/diff_chains.py`
* `CGAT/tools/chain2psl.py`

Moreover, I remember another script handling PSL file formats left out of the migration to this new repository. There is another script which produces PSL files:
* `CGAT/tools/gff2psl.py`

Can someone confirm whether these scripts are important?

Best regards,
Sebastian

**Comment by Acribbs** [comment]
Yeh I would agree that these scripts are not important, maybe others want to confirm first.

**Comment by AndreasHeger** [comment]
Indeed, we have not used them for a long time.
