### ISSUE TITLE
interrupted installation - error on $_CONDA_EXE "$cmd" "$@"

### ISSUE THREAD

**Issue by sandobits** [cgat-developers/cgat-apps#25]
I attempted installing CGAT from this new repository and encountered the following error:

><pre>
>[...]
># conda environments:
>#
>                         /home/mfl/cgat-install/conda-install
>                         /home/mfl/cgat-install/conda-install/envs/cgat-s
>                         /home/mfl/miniconda3
>                         /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]
>base                  *  /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install
>                         /home/mfl/miniconda3/envs/cgat[v0.3.3]
>                         /home/mfl/miniconda3/envs/fastqc[v0.11.7]
>                         /home/mfl/miniconda3/envs/rcorrector[v1.0.3]
>                         /home/mfl/miniconda3/envs/trim_galore[v0.5.0]
>
>sys.version: 3.7.0 | packaged by conda-forge | (defau...
>sys.prefix: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install
>sys.executable: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install/bin/python
>conda location: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install/lib/python3.7/site-packages/conda
>conda-build: None
>conda-env: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install/bin/conda-env
>user site dirs: 
>
>CIO_TEST: <not set>
>CONDA_DEFAULT_ENV: base
>CONDA_EXE: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install/bin/conda
>CONDA_PREFIX: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install
>CONDA_PROMPT_MODIFIER: (base) 
>CONDA_PYTHON_EXE: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install/bin/python
>CONDA_ROOT: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install
>CONDA_SHLVL: 1
>DEFAULTS_PATH: /usr/share/gconf/ubuntu.default.path
>MANDATORY_PATH: /usr/share/gconf/ubuntu.mandatory.path
>PATH: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install/bin:/home/mfl/miniconda3/bin:/home/mfl/bin:/home/mfl/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>REQUESTS_CA_BUNDLE: <not set>
>SSL_CERT_FILE: <not set>
>XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
>XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session0
>
>
>WARNING: could not import _license.show_info
># try:
># $ conda install -n root _license
># install-CGAT-tools.sh log | XPS-MFL | Sex Set 21 14:21:52 BRT 2018 | installing CGAT environment 
>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                 Dload  Upload   Total   Spent    Left  Speed
>100   916  100   916    0     0   1287      0 --:--:-- --:--:-- --:--:--  1286
>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                 Dload  Upload   Total   Spent    Left  Speed
>100   497  100   497    0     0   1628      0 --:--:-- --:--:-- --:--:--  1629
>Solving environment: ...working... done
></pre>
---

At which point the processing was kept with no feedback and using the 'top' process manager did not seem to indicate
anything running under cgat or cgat-apps names, so I interrupted the process with CTRL+C. I somehow needed to do it twice, and then the process encountered the errors, also apparently twice.

---

><pre>^C^C
> ##########################################################
>
> An error occurred in:
>
> - line number: 1
> - exit status: 0
> - command: $_CONDA_EXE "$cmd" "$@"
>
> The script will abort now. User input was: 
>
> ./install-CGAT-tools.sh --devel --location /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install
>
> Please copy and paste this error and report it via Git Hub: 
> https://github.com/cgat-developers/cgat-apps/issues 
>
> Debugging: 
> CFLAGS: 
> CPATH: 
> C_INCLUDE_PATH: 
> CPLUS_INCLUDE_PATH: 
> LIBRARY_PATH: 
> LD_LIBRARY_PATH: 
> CGAT_HOME: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install
> CONDA_INSTALL_DIR: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install
> CONDA_INSTALL_TYPE_APPS: apps-devel.yml
> CONDA_INSTALL_TYPE_CORE: core-devel.yml
> CONDA_INSTALL_ENV: cgat-a
> PYTHONPATH: 
> INSTALL_BRANCH: master
> CORE_BRANCH: master
> RELEASE: 
> CODE_DOWNLOAD_TYPE: 0
>
> ########################################################## 
>Solving environment: ...working... done
>^C
>CondaError: KeyboardInterrupt
>
>
> ########################################################## 
>
> An error occurred in:
>
> - line number: 1
> - exit status: 1
> - command: $_CONDA_EXE "$cmd" "$@"
>
> The script will abort now. User input was: 
>
> ./install-CGAT-tools.sh --devel --location /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install
>
> Please copy and paste this error and report it via Git Hub: 
> https://github.com/cgat-developers/cgat-apps/issues 
>
> Debugging: 
> CFLAGS: 
> CPATH: 
> C_INCLUDE_PATH: 
> CPLUS_INCLUDE_PATH: 
> LIBRARY_PATH: 
> LD_LIBRARY_PATH: 
> CGAT_HOME: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install
> CONDA_INSTALL_DIR: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install
> CONDA_INSTALL_TYPE_APPS: apps-devel.yml
> CONDA_INSTALL_TYPE_CORE: core-devel.yml
> CONDA_INSTALL_ENV: cgat-a
> PYTHONPATH: 
> INSTALL_BRANCH: master
> CORE_BRANCH: master
> RELEASE: 
> CODE_DOWNLOAD_TYPE: 0
>
> ########################################################## 
>
> ########################################################## 
>
> An error occurred in:
>
> - line number: 97
> - exit status: 1
> - command: $_CONDA_EXE "$cmd" "$@"
>
> The script will abort now. User input was: 
>
> ./install-CGAT-tools.sh --devel --location /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install
>
> Please copy and paste this error and report it via Git Hub: 
> https://github.com/cgat-developers/cgat-apps/issues 
>
> Debugging: 
> CFLAGS: 
> CPATH: 
> C_INCLUDE_PATH: 
> CPLUS_INCLUDE_PATH: 
> LIBRARY_PATH: 
> LD_LIBRARY_PATH: 
> CGAT_HOME: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install
> CONDA_INSTALL_DIR: /home/mfl/miniconda3/envs/cgat-apps[v0.5.0]/cgat-install/conda-install
> CONDA_INSTALL_TYPE_APPS: apps-devel.yml
> CONDA_INSTALL_TYPE_CORE: core-devel.yml
> CONDA_INSTALL_ENV: cgat-a
> PYTHONPATH: 
> INSTALL_BRANCH: master
> CORE_BRANCH: master
> RELEASE: 
> CODE_DOWNLOAD_TYPE: 0
>
> ########################################################## </pre>

**Comment by Acribbs** [comment]
Do you still have this issue?

**Comment by sandobits** [comment]
Sorry, I have not yet had the chance to test the solution as access to the laboratory has been restricted on specific days for a few weeks due to structural issues. I'll try again this Friday, then I'll get back to you.

Admittedly, I did not record the time elapsed until I cancelled, however, seeing as the message read "done" after solving the environment and the task manager did not show any processes under conda, cgat, cgat-apps, pip or any related names, I found it safe to assume that there was no process being worked at that moment.

**Comment by Acribbs** [comment]
because the script is installing quite heavy conda dependancies the solving environment usually indicates that conda he's resolved the dependancies and is not installing the code. It can take up to an hour at the moment. However, we are removing a lot of our dependancies (mainly R related) so the installation in the future should take less time.

**Comment by sandobits** [comment]
I have just tested the installation again and left it processing indefinitely. It eventually progressed past this, but I hit another error. Should I make a new issue concerning it or should I paste it here?

**Comment by Acribbs** [comment]
yes please submit it as a separate issue. Thanks.
