### ISSUE TITLE
devel installation fails util-linux

### ISSUE THREAD

**Issue by Acribbs** [cgat-developers/cgat-apps#26]
It seems as though the util-linux=2.21 is not available in conda https://github.com/cgat-developers/cgat-apps/blob/master/conda/environments/apps-devel.yml#L48 is there an alternative? I can see a reference to anaconda version, but no bio conda. https://anaconda.org/anaconda/util-linux

**Comment by Acribbs** [comment]
--production install with no issues

**Comment by Acribbs** [comment]
Ah, this should have been obvious to me before, but you can't install util-linux because im on a mac, doh. Anyway, installation of production version should be ok.

**Comment by jscaber** [comment]
Yes, I just tested the devel installation on Linux and it works. It also installs the new "splicing" py2.7 environment.
