### ISSUE TITLE
Exception:  Problem running command: conda info --json

### ISSUE THREAD

**Issue by sandobits** [cgat-developers/cgat-apps#32]
Currently running Linux Mint 18.3 on XFCE. I believe the error message is self-explanatory.

>Installing cgat script to /home/sand/cgat-install/conda-install/envs/cgat-a/bin
>
>
>Installed /home/sand/cgat-install/cgat-apps
>Processing dependencies for cgat==0.5.3
>Finished processing dependencies for cgat==0.5.3
>Traceback (most recent call last):
>  File "scripts/conda.py", line 47, in <module>
>    (out, err) = run_command(statement)
>  File "scripts/conda.py", line 41, in run_command
>    raise Exception(issue)
>Exception:  Problem running command: conda info --json
> Stderr was: b'/bin/bash: /home/sand/cgat-install/conda-install/envs/cgat-a/lib/libtinfo.so.5: no version >information available (required by /bin/bash)\n'
>
>
> ########################################################## 
>
> An error occurred in:
>
> - line number: 418
> - exit status: 1
> - command: python scripts/conda.py
>
> The script will abort now. User input was: 
>
> ./install.sh --devel
>
> Please copy and paste this error and report it via Git Hub: 
> https://github.com/cgat-developers/cgat-apps/issues 
>
> Debugging: 
> CFLAGS:  -I/home/sand/cgat-install/conda-install/envs/cgat-a/include -L/home/sand/cgat-install/conda-install/envs/cgat-a/lib
> CPATH:  -I/home/sand/cgat-install/conda-install/envs/cgat-a/include -L/home/sand/cgat-install/conda-install/envs/cgat-a/lib
> C_INCLUDE_PATH: :/home/sand/cgat-install/conda-install/envs/cgat-a/include
> CPLUS_INCLUDE_PATH: :/home/sand/cgat-install/conda-install/envs/cgat-a/include
> LIBRARY_PATH: :/home/sand/cgat-install/conda-install/envs/cgat-a/lib
> LD_LIBRARY_PATH: :/home/sand/cgat-install/conda-install/envs/cgat-a/lib:/home/sand/cgat-install/conda-install/envs/cgat-a/lib/R/lib
> CGAT_HOME: /home/sand/cgat-install
> CONDA_INSTALL_DIR: /home/sand/cgat-install/conda-install
> CONDA_INSTALL_TYPE_APPS: apps-devel.yml
> CONDA_INSTALL_TYPE_CORE: core-devel.yml
> CONDA_INSTALL_ENV: cgat-a
> PYTHONPATH: 
> INSTALL_BRANCH: master
> CORE_BRANCH: master
> RELEASE: 
> CODE_DOWNLOAD_TYPE: 0
>
> ##########################################################

**Comment by Acribbs** [comment]
Hi,

We have not tested the installation script on this version of Linux and it’s not clear from the log report what the obvious issue is. My first thought was that your LD_LIBRARY_PATH wasn’t set correctly but it seems as though it is.

Could you try installing the —production version of the code using the install script. 

Alternatively, could you try conda install cgat-scripts to install the code.

**Comment by sandobits** [comment]
Conda install does not seem to find the cgat-scripts packages. I tried 
> conda install cgat-scripts

as well as the the specific command on https://anaconda.org/bioconda/cgat-scripts 
> conda install -c bioconda cgat-scripts

and it resulted in

>(cgat-scripts[v0.3.2]) sand@aspire-E5-571 ~ $ conda install -c bioconda cgat-scripts
>Solving environment: failed
>
>PackagesNotFoundError: The following packages are not available from current channels:
>
>  - cgat-scripts
>  - python-lzo=1.11
>  - cgat-scripts
>  - bioconductor-ihw==1.2.0
>  - r-fdrtool
>  - cgat-scripts
>  - ggplot==0.6.8
>  - brewer2mpl
>
>Current channels:
>
>  - https://conda.anaconda.org/bioconda/linux-64
>  - https://conda.anaconda.org/bioconda/noarch
>  - https://repo.anaconda.com/pkgs/main/linux-64
>  - https://repo.anaconda.com/pkgs/main/noarch
>  - https://repo.anaconda.com/pkgs/free/linux-64
>  - https://repo.anaconda.com/pkgs/free/noarch
>  - https://repo.anaconda.com/pkgs/r/linux-64
>  - https://repo.anaconda.com/pkgs/r/noarch
>  - https://repo.anaconda.com/pkgs/pro/linux-64
>  - https://repo.anaconda.com/pkgs/pro/noarch
>
>To search for alternate channels that may provide the conda package you're
>looking for, navigate to
>
>    https://anaconda.org
>
>and use the search bar at the top of the page.

Am I missing any repositories here?
I also tried running the script with the --production parameter to which it yielded this:

>
>Installed /home/sand/cgat-install/cgat-apps
>Processing dependencies for cgat==0.5.3
>Finished processing dependencies for cgat==0.5.3
>Traceback (most recent call last):
>  File "scripts/conda.py", line 47, in <module>
>    (out, err) = run_command(statement)
>  File "scripts/conda.py", line 41, in run_command
>    raise Exception(issue)
>Exception:  Problem running command: conda info --json
> Stderr was: b'/bin/bash: /home/sand/cgat-install/conda-install/envs/cgat-a/lib/libtinfo.so.5: no version >information available (required by /bin/bash)\n'
>
>
> ########################################################## 
>
 >An error occurred in:
>
> - line number: 418
> - exit status: 1
> - command: python scripts/conda.py
>
> The script will abort now. User input was: 
>
> ./install.sh --production
>
> Please copy and paste this error and report it via Git Hub: 
> https://github.com/cgat-developers/cgat-apps/issues 
>
> Debugging: 
> CFLAGS:  -I/home/sand/cgat-install/conda-install/envs/cgat-a/include -L/home/sand/cgat-install/conda-install/envs/cgat-a/lib
> CPATH:  -I/home/sand/cgat-install/conda-install/envs/cgat-a/include -L/home/sand/cgat-install/conda-install/envs/cgat-a/lib
> C_INCLUDE_PATH: :/home/sand/cgat-install/conda-install/envs/cgat-a/include
> CPLUS_INCLUDE_PATH: :/home/sand/cgat-install/conda-install/envs/cgat-a/include
> LIBRARY_PATH: :/home/sand/cgat-install/conda-install/envs/cgat-a/lib
> LD_LIBRARY_PATH: :/home/sand/cgat-install/conda-install/envs/cgat-a/lib:/home/sand/cgat-install/conda-install/envs/cgat-a/lib/R/lib
> CGAT_HOME: /home/sand/cgat-install
> CONDA_INSTALL_DIR: /home/sand/cgat-install/conda-install
> CONDA_INSTALL_TYPE_APPS: apps-production.yml
> CONDA_INSTALL_TYPE_CORE: core-production.yml
> CONDA_INSTALL_ENV: cgat-a
> PYTHONPATH: 
> INSTALL_BRANCH: master
> CORE_BRANCH: master
> RELEASE: 
> CODE_DOWNLOAD_TYPE: 0
>
> ##########################################################

**Comment by Acribbs** [comment]
Hmm, i have just tested the installation on OSX and redhat luinx and all seems to work well.
Can you run the command:

```conda config --show-sources```
and 

```conda config --show```

Also, did you install using a clean environment?

Thanks

**Comment by sebastian-luna-valero** [comment]
Hi,

The problem seems to occur when pinning the environment:
https://github.com/cgat-developers/cgat-apps/blob/master/install.sh#L417

That wasn't performed in the CGATOxford installation.

Now that we have moved `cgat-apps` to bioconda:
http://bioconda.github.io/recipes/cgat-apps/README.html

Can I suggest that you try that instead, please?

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Please re-open if needed.
