### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Acribbs** [cgat-developers/cgat-apps#40]
Hi @sebastian-luna-valero I am in the process of packaging an environment and I require some of the newer functionality of cgat-apps in bioconda. How easy would it be to make new release and update the conda package?

I ask because I know your part of the bioconda team

**Comment by sebastian-luna-valero** [comment]
Hi,

It is a two-step process:
* Update the package in PyPI (ask @AndreasHeger if you want permissions to upload new versions)
* Update the conda recipe. No need to belong to bioconda or CGAT, you can just fork/pull request. However, it would be nice to have a ping if you do so just to keep us in the loop. I am doing it here: https://github.com/bioconda/bioconda-recipes/pull/15472

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
@AndreasHeger there is this conflict when updating the `cgat-apps` recipe:
```
16:57:43 BIOCONDA INFO (OUT) conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
16:57:43 BIOCONDA INFO (OUT)   - cython=0.27 -> python=3.6
16:57:43 BIOCONDA INFO (OUT)   - python=3.7
16:57:43 BIOCONDA INFO (OUT) Use "conda search <package> --info" to see the dependencies for each package.
```
What do you suggest?

Best regards,
Sebastian

**Comment by Acribbs** [comment]
When I was packaging a new conda package (see https://github.com/bioconda/bioconda-recipes/pull/15458#issuecomment-494068414) I had to only run builds for python 3.6 because quicksect (and cgat-apps) wasn't packaged for python 3.7 (please see https://github.com/bioconda/bioconda-recipes/pull/14770 for pull request in progress for quicksect python 3.7 release). 

Maybe for the meantime we only build for python 3.6? 

@AndreasHeger  are you able to give me the access to upload cgat-apps to pypi in a separate email?

@sebastian-luna-valero no problem in the future to ping you when building new release or build.

**Comment by sebastian-luna-valero** [comment]
xref: https://github.com/brentp/quicksect/issues/11

**Comment by sebastian-luna-valero** [comment]
FYI: cgat-apps has been updated in bioconda to v0.5.4 with both Python 3.6 and Python 3.7

**Comment by Acribbs** [comment]
Fantastic @sebastian-luna-valero! Thanks
