### ISSUE TITLE
Argparser compatibility code error

### ISSUE THREAD

**Issue by jscaber** [cgat-developers/cgat-apps#52]
File "***/cgat-developers-v2/cgat-apps/cgat/tools/bam2geneprofile.py", line 599, in main
`infile, gtf = args`
TypeError: 'Namespace' object is not iterable

**Comment by Acribbs** [comment]
Sorry thats my fault, I made changes to use argparse and I relied largely on our testing to spot mistakes, unfortunately we have gaps in our testing it seems. I suspect there will be more of these issues
