### ISSUE TITLE
pandas 1.0

### ISSUE THREAD

**Issue by sebastian-luna-valero** [cgat-developers/cgat-apps#60]
Hi,

After upgrading pandas from `0.25` to `1.0` tests are failing for `cgat-apps`.

Please check both Jenkins and Travis outputs to see the error messages.

Is there an easy fix or do we prefer to pin pandas to `<1.0` in conda environments?

Best regards,
Sebastian

**Comment by Acribbs** [comment]
Thanks @sebastian-luna-valero .

I have updated deprecated code to pandas1.0 and failing tests pass but other errors are now created: https://github.com/cgat-developers/cgat-apps/pull/61

Unfortunately I am in San Diego at the moment and the cgat code its compelling on my new Mac so I won't be able to debug this until I return next week.

**Comment by Acribbs** [comment]
I would prefer to use the latest code rather than pin, there are some really nice features in pandas 1.0.

**Comment by Acribbs** [comment]
Fixed and merged https://github.com/cgat-developers/cgat-apps/pull/61

**Comment by sebastian-luna-valero** [comment]
Many thanks, Adam!

I would like to release a new version of `cgat-apps` to reflect this update. Currently we are on `0.5.6`, should we jump to `0.6.0` this time?

Best regards,
Sebastian

**Comment by Acribbs** [comment]
Hi Sebastian,

Yeh I agree that this would make sense, do you want me to make a pypi release or do you want to do this?

BW,
Adam

**Comment by sebastian-luna-valero** [comment]
Hi Adam,

I have done it already, thanks.

I will keep an eye on bioconda trigger to package it as well there.

Best regards,
Sebastian
