### ISSUE TITLE
pysam-0.15.4 does not cgat-apps tests

### ISSUE THREAD

**Issue by sebastian-luna-valero** [cgat-developers/cgat-apps#62]
Please check output here:
https://travis-ci.org/cgat-developers/cgat-apps/builds/646576648

That's why `pysam` has been pinned on this repo to version `0.15.2`.

Until the tests pass, I propose to pin `pysam<=0.15.2` in the `cgat-flow` repository as well:
https://github.com/cgat-developers/cgat-flow/pull/128

**Comment by Acribbs** [comment]
Have tested 0.15.4 and the linux build works but not the Mac, seems like there is a problem with libhts https://travis-ci.org/github/cgat-developers/cgat-apps/jobs/687998165. There is a similar issue here but still haven't come up with a solution yet.

**Comment by Acribbs** [comment]
Hmm testing the pr worked so I merged changes. However, the testing of the master branch is giving errors again for Mac build. Given that it is only the Mac build affected and seems intermittent I won't revert the merge. I will look into this further.

Attempting to rebuild cgat-apps Conda package here: https://github.com/bioconda/bioconda-recipes/pull/22207

**Comment by Acribbs** [comment]
Actually I think I will end up reverting the merge. Its consistently breaking Mac build and I can't get Conda to package

**Comment by Acribbs** [comment]
Now testing is working this can be closed, but I will look further into why pysam output is different with later version of pysam
