### ISSUE TITLE
 module 'cgatcore.experiment' has no attribute 'ArgumentParser'

### ISSUE THREAD

**Issue by IanSudbery** [cgat-developers/cgat-apps#63]
From a user on biostars:

```
Thanks very much for this! However, I'm struggling to find documentation on the gtf2gtf tool in cgat, and in particular the flags that the tool accepts. --help gives an error:
cgat gtf2gtf --help Traceback (most recent call last): 
  File "/home/oates_binf_1/software/miniconda3/bin/cgat", line 11, in <module> sys.exit(main()) 
  File "/home/oates_binf_1/software/miniconda3/lib/python3.7/site-packages/cgat/cgat.py", line 132, in main module.main(sys.argv) 
  File "/home/oates_binf_1/software/miniconda3/lib/python3.7/site-packages/cgat/tools/gtf2gtf.py", line 362, in main parser = E.ArgumentParser(description=__doc__) 
AttributeError: module 'cgatcore.experiment' has no attribute 'ArgumentParser'
```

From someone that has just done conda install -c bioconda cgat-apps

https://www.biostars.org/p/426276/#426468

Is this another casualty of switching from ArgumentParser to OptionParser?

Is there a version mismatch between cgatcore and cgat-apps?

**Comment by IanSudbery** [comment]
Actaully, I can't find `cgat-core` listed as a requirement anywhere, let alone the version?

**Comment by Acribbs** [comment]
I think this may because the software is defaulting to an older version of cgatcore. I will fix the Conda recipe to specify the latest version of cgatcore==0.6.5

**Comment by Acribbs** [comment]
FYI latest version of cgatcore can handle both Argparse and Optparse

**Comment by Acribbs** [comment]
please see https://github.com/bioconda/bioconda-recipes/pull/20822
