### ISSUE TITLE
Error when installing CGAT

### ISSUE THREAD

**Issue by Rozita1** [cgat-developers/cgat-apps#74]
Hi,

I am trying to install CGAT and I'm getting the following error. Can you please help?
 
My previous code was:
qrshx
cd ~
wget https://github.com/cgat-developers/cgat-apps/archive/master.zip
mkdir /data/$USER/cgat_install
unzip master.zip
cd cgat-apps-master
./install.sh --production --location
 #########################################################

 An error occurred in:

 - line number: 879
 - exit status: 1
 - command: shift 2

 The script will abort now. User input was:

 ./install.sh --production --location

 Please copy and paste this error and report it via Git Hub:
 https://github.com/cgat-developers/cgat-apps/issues

 Debugging:
 CFLAGS:
 CPATH:
 C_INCLUDE_PATH:
 CPLUS_INCLUDE_PATH:
 LIBRARY_PATH:
 LD_LIBRARY_PATH:
 CGAT_HOME:
 CONDA_INSTALL_DIR:
 CONDA_INSTALL_TYPE_APPS:
 CONDA_INSTALL_TYPE_CORE:
 CONDA_INSTALL_ENV:
 PYTHONPATH:
 INSTALL_BRANCH: master
 CORE_BRANCH: master
 RELEASE:
 CODE_DOWNLOAD_TYPE: 0

 ##########################################################

**Comment by Acribbs** [comment]
Hi,

Our preferred method of installing cgat-apps is to use conda:

`conda install -c conda-forge -c bioconda cgat-apps`

If you would like to install a developmental version onto your local environment then I would suggest:

`
git clone https://github.com/cgat-developers/cgat-apps.git
cd cgat-apps
python setup.py develop
`

However, if you would like to use the install script then the reason for your error in this instance is not specifying the path for installation after the --location flag.

**Comment by Rozita1** [comment]
Thank you, just got it installed, finally.
